- name: vars file
  hosts: local
  connection: local
  vars_files:       # This is the pre-defined key for vars files
  - 06-details.yaml    # The file which we declared all the variables
  tasks:
  - name: vars file test
    ansible.builtin.debug:    # This is the module or package for debug
      msg: "The details of {{ Name }} is: Age {{ Age }}, Village {{ Village }} and PIN {{ PIN }}"