- name: Prompting
  hosts: local
  connection: local
  vars_prompt:        # This is the module for propting and it is a pre-defined key for promping vars
  - name: username    #
    prompt: What is your name?
    private: false    # This will show the input of the user while giving the input on cli
  - name: password
    prompt: What is your passwd?
    private: true     # Here we mentioned that not to show the input of the user while typing on cli
  tasks:
  - name: Prompt Testing
    ansible.builtin.debug:
      # Here we are using the values from vars_promt as variables in the message
      msg: "The username is: {{ username }} and the password is: {{ password}}"