- name: inventory-vars
  hosts: local
  connection: local
  tasks:
  - name: vars from inventory
    ansible.builtin.debug:
      # these variables are defined in the inventory.ini file and being accessed here
      msg: "This variables are from inventory file {{ Name }}, {{ Age }}"