---
- name: nginx installation
  hosts: frontend
  become: yes
  tasks:

    # - name: Update apt cache (for Debian/Ubuntu)
    #   ansible.builtin.dnf:
    #     update_cache: yes
    #     cache_valid_time: 3600

    - name: install nginx
      ansible.builtin.package:
        name: nginx
        state: present

    - name: start nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes