- name: configure frontend server
  hosts: frontend
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: present
  - name: restart nginx
    ansible.builtin.service:
      name: nginx
      state: restarted # restarted if you have already started earlier
      enabled: yes